In [2]:
import pandas as pd
import numpy as np
import belo_horizonte_real_estate_market.functions.match_info as match_info
import belo_horizonte_real_estate_market.functions.sources as dicts

In [4]:
pd.set_option('display.max_columns', None)

In [284]:
df_atividades_economicas = pd.read_parquet(path = "../data/raw_atividades_economicas.parquet")\
.assign(data_inicio_atividade = lambda df: df["data_inicio_atividade"].str.replace(r"/", "").str.replace("-", ""))\
.assign(cnae_principal = lambda df: df["cnae_principal"].str.replace("\.0", "", regex = True))\
.assign(cnae_secundarias = lambda df: df["cnae_secundarias"].str.replace("nan", "").str.split(", "))\
.assign(nome_fantasia = lambda df: df["nome_fantasia"].str.replace("nan", ""))\
.assign(complemento = lambda df: df["complemento"].str.replace("nan", ""))\
.assign(desc_logradouro = lambda df: df["desc_logradouro"].map(dicts.DATASETS["TIPO_LOGRADOURO"]))

In [285]:
df_empresarios_individuais = df_atividades_economicas\
.query("natureza_juridica.str.contains('EMPRES.RIO \(INDIVIDUAL\)')")\
[["cnpj", "nome", "nome_fantasia", "data_inicio_atividade", "nome_regional", "cnae_principal", "cnae_secundarias", "descricao_cnae", "porte_empresa", "area_utilizada", "ind_simples", "ind_mei", 
  "tipo_unidade", "forma_atuacao", "desc_logradouro", "nome_logradouro", "numero_imovel", "complemento", "nome_bairro", "geometria"]]\
.assign(ind_id = lambda df: df["nome"].str.contains(r"[0-9]{2}\.[0-9]{3}\.[0-9]{3}|[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}|[0-9]{11}|[0-9]{9}|[0-9]{3} [0-9]{3} [0-9]{3}|CPF [0-9]|CPF\:").astype(int).astype(str))\
.assign(ind_id = lambda df: df["ind_simples"] + df["ind_mei"] + df["ind_id"])\
.assign(tp_nome = lambda df: df["nome"].str.replace(r"[.\-:()\,]", "", regex = True))\
.assign(tp_nome = lambda df: df["tp_nome"].str.replace(r"[\x00-\x1F\x7F]", "", regex = True))\
.assign(tp_nome = lambda df: df["tp_nome"].str.replace(r"(?<=\d)\s+(?=\d)", "", regex = True))\
.assign(tp_nome = lambda df: df["tp_nome"].str.strip())\
.assign(tp_nome = lambda df: df["tp_nome"].str.replace("(^.+[A-Z])([0-9].+$)", "\\1 \\2", regex = True))\
.assign(tp_ = lambda df: np.where(df["ind_id"].apply(lambda x: x[2] == "1"), 0, -1))\
.assign(tp_ = lambda df: np.where(df["tp_nome"].str.contains("^.+?CPF\s+[0-9]+$").astype("int") == 1, 1, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains(".+[A-Z]CPF\s+[0-9]+")) & (df["tp_"] == 1), 8, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^[0-9]+.+$")) & (df["tp_"] == 0), 2, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^.+?\s+[0-9]+$")) & (df["tp_"] == 0), 3, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^.+?CPF[0-9]+$")) & (df["tp_"] == 0), 4, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^.+?CPF\s+[0-9]+\s+[A-Z]+")) & (df["tp_"] == 0), 5, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^.+?[0-9]+\s+[A-Z]+")) & (df["tp_"] == 0), 6, df["tp_"]))\
.assign(tp_ = lambda df: np.where((df["tp_nome"].str.contains("^.+?CPF\s+[0-9]+[A-Z]+")) & (df["tp_"] == 0), 7, df["tp_"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 1, df["tp_nome"].str.split(" CPF "), df["tp_nome"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 2, df["tp_nome"].str.replace("([0-9]+)(\s+)(.+$)", "\\3;\\1", regex = True).str.split(";"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 3, df["tp_nome"].str.replace("^(.+)(\s+)([0-9]+$)", "\\1;\\3", regex = True).str.split(";"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 4, df["tp_nome"].str.split("CPF"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 5, df["tp_nome"].str.replace("^(.+)( CPF )([0-9]+)(\s+?[A-Z]+)", "\\1;\\3", regex = True).str.split(";"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 6, df["tp_nome"].str.replace("^(.+)(\s+)([0-9]+)(\s+?[A-Z]+)", "\\1;\\3", regex = True).str.split(";"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 7, df["tp_nome"].str.replace("^(.+)(\s+CPF\s+)([0-9]+)(.+)", "\\1;\\3", regex = True).str.split(";"), df["tp_list"]))\
.assign(tp_list = lambda df: np.where(df["tp_"] == 8, df["tp_nome"].str.replace("^(.+)(CPF\s+)([0-9]+)", "\\1;\\3", regex = True).str.split(";"), df["tp_list"]))\
.assign(pessoa = lambda df: np.where(df["tp_"] == -1, df["tp_nome"], df["tp_list"].apply(lambda x: x[0])))\
.assign(cpf = lambda df: np.where(df["tp_"] == -1, "", df["tp_list"].apply(lambda x: x[1])))\
.drop(columns = ["tp_nome", "ind_id", "tp_nome", "tp_"])

In [286]:
df_empresarios_individuais["forma_atuacao"].value_counts()

forma_atuacao
ESTABELECIMENTO FIXO                                                                                                        166808
PORTA A PORTA, POSTOS MÓVEIS OU POR AMBULANTES                                                                               84898
INTERNET                                                                                                                     65078
EM LOCAL FIXO FORA DE LOJA                                                                                                   34522
ESTABELECIMENTO FIXO, INTERNET                                                                                               33198
                                                                                                                             ...
ATIVIDADES DESENVOLVIDAS FORA DO ESTABELECIMENTO, EM LOCAL FIXO FORA DE LOJA, ESTABELECIMENTO FIXO, MÁQUINAS AUTOMÁTICAS         1
CORREIO, EM LOCAL FIXO FORA DE LOJA, MÁQUINAS AUTOMÁTICAS, TELEVENDAS                                                            1
ATIVIDADES DESENVOLVIDAS FORA DO ESTABELECIMENTO, ESTABELECIMENTO FIXO, INTERNET, MÁQUINAS AUTOMÁTICAS                           1
ATIVIDADES DESENVOLVIDAS FORA DO ESTABELECIMENTO, INTERNET, MÁQUINAS AUTOMÁTICAS                                                 1
CORREIO, ESTABELECIMENTO FIXO, MÁQUINAS AUTOMÁTICAS, TELEVENDAS                                                                  1
Name: count, Length: 183, dtype: int64

In [287]:
df_empresarios_individuais.query("ind_simples == 'N'")

,cnpj,nome,nome_fantasia,data_inicio_atividade,nome_regional,cnae_principal,cnae_secundarias,descricao_cnae,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,geometria,tp_list,pessoa,cpf
index,,,,,,,,,,,,,,,,,,,,,,,
43,70986948000143,ROBSON SALES HENEDINO,,01041993,NORDESTE,4520001,"[4520002, 4520003, 4520004]",SERVICOS DE MANUTENCAO E REPARACAO MECANICA DE...,MICROEMPRESA - ME,150.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,DOUTOR BENJAMIM MOSS,319,,UNIAO,POINT (613033.200778877 7800638.00374008),ROBSON SALES HENEDINO,ROBSON SALES HENEDINO,
109,18716712000177,ANTONIO HENRIQUES DA SILVA,BILHARES CEU AZUL,02011975,VENDA NOVA,3240002,[3240003],"FABRICACAO DE MESAS DE BILHAR, DE SINUCA E ACE...",MICROEMPRESA - ME,56.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,AVELINO GIAROLA,475,LOJA 1,CEU AZUL,POINT (604815.573078683 7807629.62889447),ANTONIO HENRIQUES DA SILVA,ANTONIO HENRIQUES DA SILVA,
119,71065932000160,EDUARDO FERREIRA DA SILVA,SUPERMERCADO SAO GERALDO,10051993,LESTE,4711302,[],"COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, CO...",MICROEMPRESA - ME,417.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,PRACA,SANTUARIO SAO GERALDO,151,,SAO GERALDO,POINT (615316.549277029 7799479.17961538),EDUARDO FERREIRA DA SILVA,EDUARDO FERREIRA DA SILVA,
193,42994152000105,FABIO KALKS KOSCKY,BAR DO FABIO,01011993,NOROESTE,5611203,[],SORVETERIA,MICROEMPRESA - ME,23.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVENIDA,TRINTA E UM DE MARCO,390,A,DOM CABRAL,POINT (605097.201696115 7796886.79798928),FABIO KALKS KOSCKY,FABIO KALKS KOSCKY,
201,23951874000120,DALMO BECATTINI FILHO,MERCEARIA ESQUININHA,01031993,NOROESTE,4729699,[4712100],COMERCIO VAREJISTA DE PRODUTOS ALIMENTICIOS EM...,MICROEMPRESA - ME,50.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CANTAGALO,821,,APARECIDA,POINT (609719.880503579 7800057.78886091),DALMO BECATTINI FILHO,DALMO BECATTINI FILHO,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453286,11267429000166,ITAMERES MOREIRA SALOMAO DO SANTO,,02092021,nan,9602502,"[4772500, 9602502]",ATIVIDADES DE ESTÉTICA E OUTROS SERVIÇOS DE CU...,EMPRESA DE PEQUENO PORTE,81.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,SAO PAULO,1966,"SALA:401,",LOURDES,POINT (610590.27 7795834.87),ITAMERES MOREIRA SALOMAO DO SANTO,ITAMERES MOREIRA SALOMAO DO SANTO,
1463926,18946854000120,MARCIA ELISA GUEDES CONCEICAO 02691869644,,25092013,nan,1412601,"[1412601, 3299099]","CONFECCAO DE PECAS DO VESTUARIO, EXCETO ROUPAS...",MICROEMPRESA - ME,10.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,MARY APARECIDA,186,,JARDIM SAO JOSE,POINT (605177.15 7799017.97),"[MARCIA ELISA GUEDES CONCEICAO, 02691869644]",MARCIA ELISA GUEDES CONCEICAO,02691869644
1488477,13647909000188,DUILIO DUTRA FILHO,,09012024,nan,4221905,[4221905],MANUTENCAO DE ESTACOES E REDES DE TELECOMUNICA...,MICROEMPRESA - ME,10.0,N,N,UNIDADE PRODUTIVA,"PORTA A PORTA, POSTOS MÓVEIS OU POR AMBULANTES",RUA,RIO GRANDE DO NORTE,1435,SALA 708,SAVASSI,POINT (611699.07 7795022.80),DUILIO DUTRA FILHO,DUILIO DUTRA FILHO,
1501870,30173422000120,G. M. FERREIRA PERSIANAS,G M FERREIRA,11042018,nan,4759801,"[1351100, 1354500, 3329599, 4330499, 4649405, ...","COMERCIO VAREJISTA DE ARTIGOS DE TAPECARIA, C...",MICROEMPRESA - ME,10.0,N,N,ESCRITÓRIO ADMINSTRATIVO,nan,RUA,MARECHAL FALCONIERE,967,,EUROPA,POINT (608384.70 7810386.82),G M FERREIRA PERSIANAS,G M FERREIRA PERSIANAS,
1536699,36741059000188,HUGO MARCIO LEMOS TEIXEIRA ASSESSORIA DE COMUN...,HUGO TEIXEIRA ASSESSORIA DE COMUNICACAO,20032020,nan,7020400,"[5911199, 5912099, 7020400, 8592902, 9001901, ...",ATIVIDADES DE CONSULTORIA EM GESTAO EMPRESARIA...,MICROEMPRESA - ME,20.0,N,N,SEDE,nan,AVENIDA,CRISTIANO MACHADO,1587,APT 604,SILVEIRA,POINT (612208.74 7799919.72),HUGO MARCIO LEMOS TEIXEIRA ASSESSORIA DE COMUN...,HUGO MARCIO LEMOS TEIXEIRA ASSESSORIA DE COMUN...,

In [291]:
df_atividades_economicas\
.query("cnae_principal == '8112500'")["natureza_juridica"].value_counts()

natureza_juridica
CONDOMÍNIO EDILÍCIO                   26165
ASSOCIAÇÃO PRIVADA                       42
SOCIEDADE EMPRESÁRIA LIMITADA            12
CONSÓRCIO DE SOCIEDADES                   2
SOCIEDADE SIMPLES LIMITADA                2
SOCIEDADE EM CONTA DE PARTICIPAÇÃO        1
COMUNIDADE INDÍGENA                       1
Name: count, dtype: int64

In [301]:
df_condominios_cnpjs = df_atividades_economicas\
.query("natureza_juridica == 'CONDOMÍNIO EDILÍCIO'")\
[["cnpj", "nome", "nome_fantasia", "data_inicio_atividade", "nome_regional", "cnae_principal", "cnae_secundarias", "descricao_cnae", "porte_empresa", "area_utilizada", "ind_simples", "ind_mei", 
  "tipo_unidade", "forma_atuacao", "desc_logradouro", "nome_logradouro", "numero_imovel", "complemento", "nome_bairro", "geometria"]]

In [336]:
df_condominios_cnpjs

,cnpj,nome,nome_fantasia,data_inicio_atividade,nome_regional,cnae_principal,cnae_secundarias,descricao_cnae,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,geometria
index,,,,,,,,,,,,,,,,,,,,
2411,65162380000106,CONDOMINIO MINAS SHOPPING,,25091991,NORDESTE,8112500,"[5223100, 9329899]",CONDOMINIOS PREDIAIS,DEMAIS,16895.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVENIDA,CRISTIANO MACHADO,4000,,UNIAO,POINT (612416.154541622 7801830.90704951)
10211,19794254000157,CONDOMINIO GALERIA OUVIDOR,,01102000,CENTRO-SUL,8112500,[9609299],CONDOMINIOS PREDIAIS,DEMAIS,80.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CURITIBA,715,,CENTRO,POINT (610812.067175938 7797128.25813863)
12297,4782680000101,CONDOMINIO DO EDIFICIO AFONSO PENA FLAT SERVICE,,27042000,CENTRO-SUL,8112500,[],CONDOMINIOS PREDIAIS,DEMAIS,100.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVENIDA,AFONSO PENA,3761,,SERRA,POINT (612655.663545189 7794450.97968948)
20991,65172074000150,CONDOMINIO SOLDADO WILSON TRINDADE,,19021992,NOROESTE,8112500,[],CONDOMINIOS PREDIAIS,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,ANTONIO PEIXOTO,91,,COQUEIROS,POINT (602153.435914513 7799276.76081714)
21916,9198026000160,CONDOMINIO EDIFICIO ITUIUTABA,,19072007,OESTE,8112500,[],CONDOMINIOS PREDIAIS,DEMAIS,643.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CONSELHEIRO JOAQUIM CAETANO,223,,NOVA GRANADA,POINT (607785.270531208 7794969.23767373)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1367953,63209545000122,CONDOMINIO PAMPULHA,,04092025,nan,8112500,[8112500],CONDOMINIOS PREDIAIS,DEMAIS,10.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVENIDA,FLEMING,510,,OURO PRETO,POINT (606165.02 7802623.63)
1368324,25467952000140,CONDOMINIO DO EDIFICIO PALERMO,,18072025,nan,8112500,[8112500],CONDOMINIOS PREDIAIS,DEMAIS,10.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,PROFESSOR NELSON DE SENA,115,,AEROPORTO,POINT (609113.11 7804142.15)
1412057,4133916000170,CONDOMINIO DO RESIDENCIAL OHIO - BLOCO 04,,08112000,nan,8112500,[8112500],CONDOMINIOS PREDIAIS,DEMAIS,10.0,N,N,UNIDADE PRODUTIVA,nan,RUA,HENRIQUE FURTADO PORTUGAL,180,BLOCO 04,BURITIS,POINT (608195.15 7791098.83)
1414200,4353270000137,CONDOMINIO DO EDIFICIO OLINDA F. CAMARGOS,,20031995,nan,8112500,[8112500],CONDOMINIOS PREDIAIS,DEMAIS,10.0,N,N,UNIDADE PRODUTIVA,nan,RUA,DOUTOR FURTADO DE MENEZES,767,,IPIRANGA,POINT (611907.40 7801115.16)
1445819,63131266000193,EVOLUTION,,05062023,nan,8112500,[8112500],CONDOMINIOS PREDIAIS,DEMAIS,10.0,N,N,SEDE,nan,RUA,MARIA HEILBUTH SURETTE,1312,QUADRARUA IRACY MANATA195,BURITIS,POINT (607621.39 7791759.56)

In [ ]:
pd.DataFrame(df_condominios_cnpjs["nome"].str.split(" ").to_list())\
.stack().value_counts().reset_index().sort_values("index")\
["index"].to_list()[2000:3000]

# C0NDOMINIO, CNDOMINIO, CODOMINIO, COND, COND. 'CONDIMINIO',
 'CONDMINIO',
 'CONDOIMINIO',
 'CONDOMIINIO',
 'CONDOMIIO',
 'CONDOMIMIO',
 'CONDOMIMNIO',
 'CONDOMIN',
 'CONDOMINI0',
 'CONDOMINIIO',
 'CONDOMININIO',
 'CONDOMININO',
 'CONDOMINIO', CONDOMINJIO, 'CONDOMINMIO',
 'CONDOMINNIO',
 'CONDOMINO',
 'CONDOMINOS',
 'CONDOMIO',
 'CONDOMIONIO',
 'CONDOMN',
 'CONDOMNIO',
 'CONDOMONIO',
 'CONDOMÌNIO',
 'CONDOMÍNIO',
 'CONDONIMIO',
 'CONDONINIO', 'CONMDOMINIO',
 'CONODMINIO',
 'CONOMINIO',

['CIO',
 'CIOLETTI',
 'CIOTTO',
 'CIPO',
 'CIPRESTE',
 'CIPRIANI',
 'CIPRIANO',
 'CIPROS',
 'CIRA',
 'CIRCE',
 'CIRELI',
 'CIRIACO',
 'CIRILO',
 'CIRIUS',
 'CIRO',
 'CIRRUS',
 'CISA',
 'CISNE',
 'CITE',
 'CITIBANK',
 'CITINUS',
 'CITRINO',
 'CITTA',
 'CITY',
 'CIVENA',
 'CIVETTA',
 'CIVIL',
 'CLA',
 'CLAIR',
 'CLAIRE',
 'CLARA',
 'CLARAS',
 'CLARET',
 "CLARET''",
 'CLARICE',
 'CLARINDA',
 'CLARION',
 'CLARISSA',
 'CLARO',
 'CLAROS',
 'CLASS',
 'CLASSIC',
 'CLASSICA',
 'CLAUDE',
 'CLAUDEL',
 'CLAUDIA',
 'CLAUDIANO',
 'CLAUDIENSE',
 'CLAUDINA',
 'CLAUDINO',
 'CLAUDIO',
 'CLAUDIOMAR',
 'CLAUDIONOR',
 'CLAUDOVALDO',
 'CLAUSIO',
 'CLAVE',
 'CLEIDE',
 'CLELIA',
 'CLEMENT',
 'CLEMENTE',
 'CLEMENTINO',
 'CLEONICE',
 'CLERMOND',
 'CLERMONT',
 'CLERY',
 'CLEUZA',
 'CLEVELAND',
 'CLIMA',
 'CLINICA',
 'CLOCO',
 'CLODOVEL',
 'CLODOVEU',
 'CLORIS',
 'CLOTILDE',
 'CLOVIS',
 'CLUB',
 'CLUBE',
 'CNDOMINIO',
 'COBALTO',
 'COBAP',
 'COBERIO',
 'COBRA',
 'COBUCCI',
 'COCAIS',
 'COD',
 'CODO',
 'CODOMINIO',
 'COELHO',
 'COELI',
 'COFERMETA',
 'COHEN',
 'COHN',
 'COIMBRA',
 'COJUNTO',
 'COL',
 'COLEIRINHA',
 'COLEN',
 'COLETA',
 'COLI',
 'COLIBRI',
 'COLIBRIS',
 'COLINA',
 'COLINAS',
 'COLISEUM',
 'COLLE',
 'COLLIN',
 'COLLINE',
 'COLOMBAROLI',
 'COLOMBAROLLI',
 'COLOMBIA',
 'COLOMBO',
 'COLONIA',
 'COLONIAL',
 'COLONNA',
 'COLORADO',
 'COLORE',
 'COLUMBIA',
 'COLUMBUS',
 'COMACHIO',
 'COMANCHES',
 'COMANDANTE',
 'COMANDATUBA',
 'COMANDUCCI',
 'COMARA',
 'COMCENTER',
 'COMCENTERES',
 'COMCENTERS',
 'COMDIMINIO',
 'COMDOMINIO',
 'COMENDADOR',
 'COMERCIAL',
 'COMERCIAL-RESIDENCIAL',
 'COMERCIAL/RESIDENCIAL',
 'COMERCIO',
 'COMETA',
 'COMFORT',
 'COMINI',
 'COMITECO',
 'COMJUNTO',
 'COMMERCE',
 'COMODORO',
 'COMPLEXO',
 'COMPOSSUIDORES',
 'COMPOSTELA',
 'COMPOSTELLE',
 'COMUM',
 'CON',
 'CONCEICAO',
 'CONCENTINO',
 'CONCESSO',
 'CONCHAS',
 'CONCOMINIO',
 'CONCORD',
 'CONCORDE',
 'COND',
 'COND.',
 'COND.BL',
 'COND.CONJ.HAB.DR.RODRIGO',
 'COND.DO',
 'COND.ED.',
 'COND.ED.BELVEDERE',
 'COND.ED.PORTAL',
 'COND.EDFICIO',
 'COND.EDIFICIO',
 'CONDADO',
 'CONDE',
 'CONDIMINIO',
 'CONDMINIO',
 'CONDOIMINIO',
 'CONDOMIINIO',
 'CONDOMIIO',
 'CONDOMIMIO',
 'CONDOMIMNIO',
 'CONDOMIN',
 'CONDOMINI0',
 'CONDOMINIIO',
 'CONDOMININIO',
 'CONDOMININO',
 'CONDOMINIO',
 'CONDOMINIO-RESIDENCIAL',
 'CONDOMINIODAS',
 'CONDOMINIODO',
 'CONDOMINIOO',
 'CONDOMINIOS',
 'CONDOMINJIO',
 'CONDOMINMIO',
 'CONDOMINNIO',
 'CONDOMINO',
 'CONDOMINOS',
 'CONDOMIO',
 'CONDOMIONIO',
 'CONDOMN',
 'CONDOMNIO',
 'CONDOMONIO',
 'CONDOMÌNIO',
 'CONDOMÍNIO',
 'CONDONIMIO',
 'CONDONINIO',
 'CONDONIO',
 'CONDOR',
 'CONDOTTI',
 'CONEEV',
 'CONEEVI',
 'CONEGO',
 'CONENGE',
 'CONFIANCA',
 'CONFORT',
 'CONGONHAS',
 'CONJ',
 'CONJ.',
 'CONJ.HAB.RESIDENCIAL',
 'CONJ.RESIDENCIAL',
 'CONJUNTO',
 'CONMDOMINIO',
 'CONODMINIO',
 'CONOMINIO',
 'CONQUISTA',
 'CONQUISTARE',
 'CONRADO',
 'CONRENNO',
 'CONSEL',
 'CONSELHEIRO',
 'CONSPLAN',
 'CONSTANCA',
 'CONSTANCE',
 'CONSTANCIA',
 'CONSTANTINO',
 'CONSTELACAO',
 'CONSTELACOES',
 'CONSTELATION',
 'CONSTRUCOES',
 'CONSUELO',
 'CONSUL',
 'CONSULTORIO',
 'CONSULTORIOS',
 'CONTAGEM',
 'CONTEMPORANEO',
 'CONTENDAS',
 'CONTENTO',
 'CONTI',
 'CONTINENTAL',
 'CONTORNO',
 'CONTRIA',
 'CONUNTO',
 'CONVENIENCIA',
 'CONVENTION',
 'CONVENTIONS',
 'CONVIVA',
 'CONVIVENCE',
 'COOMINO',
 'COOPEBEL',
 'COOPERAR',
 'COOPERATIVA',
 'COOPSOMG',
 'COPACABANA',
 'COPENHAGEN',
 'COPERNICO',
 'COQUEIRO',
 'COQUEIROS',
 'CORA',
 'CORACAO',
 'CORACOES',
 'CORAIS',
 'CORAL',
 'CORALINA',
 'CORBUSIER',
 'CORCINI',
 'CORCOVADO',
 'CORDEIRO',
 'CORDOBA',
 'CORDOVA',
 'CORDOVIL',
 'CORDULINA',
 'CORENNO',
 'COREU',
 'CORFU',
 'CORICANCHA',
 'CORINA',
 'CORINTA',
 'CORINTHA',
 'CORINTO',
 'CORNELIO',
 'COROACI',
 'COROMANDEL',
 'CORONADO',
 'CORONEL',
 'CORPORATE',
 'CORPORATIVO',
 'CORRADI',
 'CORREA',
 'CORREIA',
 'CORREIAS',
 'CORRIENTES',
 'CORSEGA',
 'CORSINI',
 'CORSO',
 'CORTE',
 'CORTES',
 'CORTINA',
 'CORTTES',
 'CORUNA',
 'COSCARELLI',
 'COSENZA',
 'COSME',
 'COSMOS',
 'COSSENZO',
 'COSTA',
 'COSTAGRANDI',
 'COTA',
 'COTE',
 'COTIGNOLA',
 'COTTA',
 'COULAUD',
 'COURA',
 'COURCHEVEL',
 'COURI',
 'COURI.',
 'COUTINHO',
 'COUTO',
 'COVILHA',
 'COWAN',
 'COZUMEL',
 'CRAVINAS',
 'CRAVO',
 'CREDIPREV',
 'CREDIPREV-CASB',
 'CREDIPREV/CASB',
 'CREGO',
 'CRETA',
 'CREUZA',
 'CRIANCADA',
 'CRICARE',
 'CRIS-MAR',
 'CRISANDALIA',
 'CRISANTEMOS',
 'CRISPIN',
 'CRIST',
 "CRIST'ANA",
 'CRISTAIS',
 'CRISTAL',
 'CRISTALINA',
 'CRISTALLI',
 'CRISTIANA',
 'CRISTIANE',
 'CRISTIANI',
 'CRISTIANNA',
 'CRISTIANO',
 'CRISTINA',
 'CRISTINE',
 'CRISTINI',
 'CRISTO',
 'CRISTOVAO',
 'CRISTYANO',
 'CRIVELLARI',
 'CRJ',
 'CROMWELL',
 'CRONOS',
 'CROSLAND',
 'CROTALUS',
 'CRUCIS',
 'CRUVINEL',
 'CRUZ',
 'CRUZEIRO',
 'CRUZES',
 'CRYSTAL',
 'CUBAS',
 'CUBATAO',
 'CUCUERA',
 'CUIABA',
 'CUNHA',
 'CUPERTINO',
 'CURA',
 'CURI',
 'CURIMATA',
 'CURITIBA',
 'CURITIBANOS',
 'CURRAL',
 'CURVELO',
 'CURY',
 'CUSTODIO',
 'CYGNUS',
 'CYLMARA',
 'CYNARA',
 'CYNTHIA',
 'CYPRESTE',
 'CYRA',
 'CYRINO',
 'CYRO',
 'D',
 "D'AGUA",
 "D'AIRE",
 "D'AIRES",
 "D'ALGARVE",
 "D'ALHO",
 "D'ALICE",
 "D'ALVA",
 "D'AMBROSIO",
 "D'AMPEZZO",
 "D'ANGELO",
 "D'ANGERS",
 "D'ANTIBES",
 "D'AOSTA",
 "D'ARC",
 "D'ARGENT",
 "D'ARGENTO",
 "D'ARS",
 "D'ARTIGNY",
 "D'ASSISI",
 "D'ASSUMPCAO",
 "D'AVILA",
 "D'AZUR",
 "D'ECLAIR",
 "D'EL",
 "D'ESPANHA",
 "D'ESTE",
 "D'FONTI",
 "D'ITALIA",
 "D'LUCCA",
 "D'MARIA",
 "D'OLAVO",
 "D'OR",
 "D'ORLEANS",
 "D'ORLY",
 "D'ORO",
 "D'ORSAY",
 "D'OURO",
 "D'OUROS",
 "D'OUTONO",
 "D'PAULA",
 "D'QUEBEC",
 "D'VINCI",
 'D.',
 'D.GUILHERMINA',
 'D.ISABEL',
 'D.ISAURA',
 'D.IZABEL',
 'D.MARIQUITA',
 'D.PEDRO',
 'D0',
 'D0N',
 'D1',
 'D?ARS',
 'DA',
 'DACIO',
 'DADE',
 'DADIVA',
 'DAHER',
 'DAIBERT',
 'DAISE',
 'DAKAR',
 'DAKOTA',
 'DALADIER',
 'DALARA',
 'DALHO',
 'DALI',
 'DALILA',
 'DALKER',
 'DALLA',
 'DALLAS',
 'DALLI',
 'DALMO',
 'DALVA',
 'DALVINA',
 'DAMA',
 'DAMASCENO',
 'DAMASCO',
 'DAMATA',
 'DAMAZO',
 'DAME',
 'DAMIAO',
 'DAMIGO',
 'DAMPEZZO',
 'DANDARA',
 'DANI',
 'DANIEL',
 'DANIELA',
 'DANIELE',
 'DANIELL',
 'DANIELLA',
 'DANIELLE',
 'DANIELLY',
 'DANILO',
 'DANNTHY',
 'DANNY',
 'DANTAS',
 'DANTE',
 'DANTES',
 'DANTIBES',
 'DANTON',
 'DANUBIO',
 'DANY',
 'DARCI',
 'DARCY',
 'DARDOT',
 'DARGENTO',
 'DARLES',
 'DARLEY',
 'DARS',
 'DARTAGNAN',
 'DARWEN',
 'DAS',
 'DASDORES',
 'DATASINC',
 'DAUCA',
 'DAURA',
 'DAVDSON',
 'DAVI',
 'DAVID',
 'DAVIDSON',
 'DAVIGNON',
 'DAVILA',
 'DAVIS',
 'DAVOS',
 'DAWAHRI',
 'DAYREL',
 'DAYRELL',
 'DAYSE',
 'DBA',
 'DCOR',
 'DE',
 'DEA',
 'DEAUVILLE',
 'DEBBIO',
 'DEBIR',
 'DEBORA',
 'DEBORAH',
 'DEBOSSAN',
 'DEBRET',
 'DECIO',
 'DECK&SOL',
 'DECO',
 'DEFELIPPO',
 'DEFENSE',
 'DEFEO',
 'DEGAS',
 'DEI',
 'DEIA',
 'DEISE',
 'DEL',
 "DEL'REY",
 'DELAMARQUE',
 'DELANE',
 'DELANNE',
 'DELCIO',
 'DELCY',
 'DELE',
 'DELFIM',
 'DELFINO',
 'DELFIORI',
 'DELFOS',
 'DELFRAN',
 'DELGADA',
 'DELGADO',
 'DELHI',
 'DELIVERY',
 'DELL',
 'DELLA',
 'DELLAVAR',
 'DELLE',
 'DELLOS',
 'DELMIRACOLO',
 'DELPHOS',
 'DELPHUS',
 'DELTA',
 'DELTHA',
 'DEMETRIO',
 'DEMIEN',
 'DEMINAS',
 'DEMOCRATAS',
 'DEMOISELLE',
 'DENI',
 'DENIDIA',
 'DENIS',
 'DENISA',
 'DENISE',
 'DENIZE',
 'DENNIS',
 'DENNYS',
 'DENUCCI',
 'DENVER',
 'DEO',
 'DEOCRISTE',
 'DEOLINDA',
 'DEPUTADO',
 'DERBY',
 'DERMINAS',
 'DERNA',
 'DES',
 'DESCHAMPS',
 'DESEMBARGADOR',
 'DESIGN',
 'DESJARDINS',
 'DESLANDES',
 'DESPACHO',
 'DESPANHA',
 'DESSAR',
 'DESTINO',
 'DETROID',
 'DETROIT',
 'DEU',
 'DEUS',
 'DEVILE',
 'DEVILLE',
 'DEYSE',
 'DEZ',
 'DEZEMBRO',
 'DEZOITO',
 'DHABI',
 'DHELI',
 'DI',
 'DIADEMA',
 'DIADORIM',
 'DIAMANT',
 'DIAMANTE',
 'DIAMANTES',
 'DIAMANTINA',
 'DIAMANTINE',
 'DIAMETRAL',
 'DIAMIL',
 'DIAMOND',
 'DIANA',
 'DIANIL',
 'DIANO',
 'DIAS',
 'DICA',
 'DIDITA',
 'DIEB',
 'DIEGO',
 'DIEM',
 'DIFICIO',
 'DIJON',
 'DILA',
 'DILIA',
 'DILINHA',
 'DILSON',
 'DIMAS',
 'DINA',
 'DINAH',
 'DINAMARCA',
 'DINAMICO',
 'DINAMO',
 'DINISA',
 'DINIZ',
 'DINORAH',
 'DIOGO',
 'DIOLETA',
 'DIOLINDA',
 'DIOMAR',
 'DION',
 'DIONISIO',
 'DIONIZIO',
 'DIORIO',
 'DIRCE',
 'DIRCEM',
 'DIRCEU',
 'DIVA',
 'DIVALDO',
 'DIVINA',
 'DIVINO',
 'DIVINOPOLIS',
 'DJALMA',
 'DJANIRA',
 'DK',
 'DM',
 'DMA',
 'DO',
 'DO.',
 'DOCARMO',
 'DOCE',
 'DODORA',
 'DOEDIFICIO',
 'DOEHLEE',
 'DOEHLER',
 'DOHA',
 'DOIA',
 'DOIS',
 'DOLABELA',
 'DOLABELLA',
 'DOLCE',
 'DOLLINGER',
 'DOLOMITA',
 'DOLORES',
 'DOM',
 'DOMANI',
 'DOMASO',
 'DOMENICO',
 'DOMICIO',
 'DOMINATUS',
 'DOMINGOS',
 'DOMINGUES',
 'DOMINGUEZ',
 'DOMINICANOS',
 'DOMINICK',
 'DOMINUS',
 'DOMINUS-I',
 'DOMITILA',
 'DOMREMY',
 'DOMUS',
 'DON',
 'DONA',
 'DONAILDA',
 'DONALESA',
 'DONANA',
 'DONARIA',
 'DONAROSA',
 'DONATELLI',
 'DONATELLO',
 'DONATO',
 'DONDON',
 'DONNA',
 'DOPODOMANI',
 'DOR',
 'DORA',
 'DORALICE',
 'DORES',
 'DORIA',
 'DORIAN',
 'DORINHA',
 'DORIVAL',
 'DORLEANS',
 'DORLY',
 'DORNELAS',
 'DORNFELD',
 'DOROLI',
 'DOROTEIA',
 'DOROTHEA',
 'DORSAY',
 'DORVALINA',
 'DORVINA',
 'DOS',
 'DOURADA',
 'DOURADO',
 'DOURO',
 'DOUTOR',
 'DOWNTOWN',
 'DQUEBEC',
 'DR',
 'DR.',
 'DR.ANTONIO',
 'DR.ARMANDO',
 'DR.EMILIO',
 'DR.FABIO',
 'DR.GERASSO',
 'DR.JOSE',
 'DR.JUSTO',
 'DR.OMAR',
 'DR.PAULO',
 'DR.ROBERTO',
 'DR.SEBASTIAO',
 'DR.ZICA',
 'DRA',
 'DRA.',
 'DRACENA',
 'DREAM',
 'DREAMS',
 'DRUMMOND',
 'DRUMOND',
 'DU',
 'DUARTE',
 'DUARTE.',
 'DUARTINA',
 'DUAS',
 'DUBAI',
 'DUBLIN',
 'DUCALE',
 'DUDA',
 'DUE',
 'DUETTO',
 'DUGALE',
 'DUJON',
 'DUKE',
 'DULCE',
 'DULCINEI',
 'DUMBA',
 'DUMONT',
 'DUNA',
 'DUNALVA',
 'DUNCAN',
 'DUO',
 'DUOMO',
 'DUPLA',
 'DUQUE',
 'DUQUESA',
 'DURAES',
 'DURAO',
 'DURCO',
 'DURKHEIM',
 'DURVAL',
 'DURVALINA',
 'DUSKY',
 'DUTRA',
 'DUVAL',
 'DUZENTOS',
 'E',
 'E.',
 'EASY',
 'EBANO',
 'EBENESE',
 'EBENEZER',
 'EBER',
 'ECA',
 'ECKNER',
 'ECLIPSE',
 'ECO',
 'ECY',
 'ED',
 'ED.',
 'ED.ANTONIO',
 'ED.BRUXELAS',
 'ED.CARLOS',
 'ED.CIDADE',
 'ED.DANILO',
 'ED.DONA',
 'ED.JARDIM',
 'ED.LUCIANA',
 'ED.MESTRE',
 'ED.MONTREAL',
 'ED.RAIMUNDO',
 'ED.RESIDENCIAL',
 'ED.SAINT',
 'ED.SELENIO',
 'ED.SERGIO',
 'ED.SOUZA',
 'ED.STELLA',
 'ED.TOP',
 'ED.VIOLETA',
 'EDELWEISS',
 'EDEN',
 'EDENLAR',
 'EDF',
 'EDF.',
 'EDFICIO',
 'EDGAR',
 'EDGARD',
 'EDICICIO',
 'EDICIFIO',
 'EDICIO',
 'EDIDFICIO',
 'EDIDIFICIO',
 'EDIDIFICO',
 'EDIF',
 'EDIF.',
 'EDIF.ANITA',
 'EDIF.JOAO',
 'EDIF.JOSE',
 'EDIF.VAN',
 'EDIFCIO',
 'EDIFI',
 'EDIFIC',
 'EDIFICI',
 'EDIFICI0',
 'EDIFICIIO',
 'EDIFICIL',
 'EDIFICIO',
 'EDIFICIOALEXANDRE',
 'EDIFICIOFRANCISCO',
 'EDIFICIOO',
 'EDIFICIOP',
 'EDIFICIOS',
 'EDIFICO',
 'EDIFIICIO',
 'EDIFIIO',
 'EDIFIO',
 'EDIFÍCIO',
 'EDIIFICIO',
 'EDILA',
 'EDILENE',
 'EDILICIO',
 'EDIMBURGO',
 'EDIRANE',
 'EDISA',
 'EDISON',
 'EDITE',
 'EDITH',
 'EDLA',
 'EDMAR',
 'EDMEA',
 'EDMILA',
 'EDMILSON',
 'EDMONTON',
 'EDMUNDO',
 'EDNA',
 'EDNEY',
 'EDSON',
 'EDUARDA',
 'EDUARDO',
 'EDUMAR',
 'EDVARD',
 'EDWIGES',
 'EDWIRGES',
 'EDY',
 'EFICICIO',
 'EFIDICIO',
 'EFIFICIO',
 'EFIGENIA',
 'EGARIO',
 'EGAS',
 'EGEU',
 'EGITO',
 'EGYDIO',
 'EICOM',
 'EIDIFICIO',
 'EIFEL',
 'EIFFEL',
 'EIFICIO',
 'EILAT',
 'EIMAR',
 'EINSTEIN',
 'EL',
 'ELADIO',
 'ELAINE',
 'ELANUS',
 'ELBA',
 'ELBACHA',
 'ELBRUS',
 'ELCONDOR',
 'ELDA',
 'ELDORADO',
 'ELECTRA',
 'ELEGANCE',
 'ELEN',
 'ELENA',
 'ELEONORA',
 'ELET',
 'ELEUTERIO',
 'ELEVAR',
 'ELFRIEDE',
 'ELI',
 'ELIAN',
 'ELIANA',
 'ELIANA.',
 'ELIANE',
 'ELIAS',
 'ELIATA',
 'ELIAZAR',
 'ELIDIO',
 'ELIM',
 'ELIN',
 'ELIO',
 'ELIODORO',
 'ELISA',
 'ELISABETH',
 'ELISEOS',
 'ELISEU',
 'ELISIO',
 'ELIZA',
 'ELIZABETE',
 'ELIZABETH',
 'ELIZETH',
 'ELKA',
 'ELL',
 'ELLEGANCE',
 'ELLEN',
 'ELLETA',
 'ELLINGTON',
 'ELMAR',
 'ELMIRA',
 'ELMO',
 'ELNIZE',
 'ELO',
 'ELOA',
 'ELOHIM',
 'ELOI',
 'ELOIM',
 'ELOISA',
 'ELOIZA',
 'ELOYSI',
 'ELPIDIO',
 'ELSHADAY',
 'ELU',
 'ELVAS',
 'ELVIRA',
 'ELZA',
 'ELZI',
 'ELZIRA',
 'EMA',
 'EMANUEL',
 'EMANUELA',
 'EMANUELLE',
 'EMAUS',
 'EMBAUBA',
 'EMBLEMA',
 'EMBUIA',
 'EMC',
 'EMERENCIANA',
 'EMERENTINA',
 'EMERY',
 'EMETERIO',
 'EMIDIA',
 'EMIDIO',
 'EMILE',
 'EMILIA',
 'EMILIAN',
 'EMILIANO',
 'EMILIO',
 'EMILION',
 'EMOTION',
 'EMPAL',
 'EMPREENDEDORES',
 'EMPREENDIMENTO']

In [ ]:
df_condominios_cnpjs\
.assign(nome_condominio = lambda df: df["nome"].str.replace("[\'\-]", "", regex = True).str.replace("\s+", " ", regex = True).str.strip())\
.assign(nome_condominio = lambda df: df["nome_condominio"].str.replace("CONDOMINIO ", "", regex = True))\
.sort_values("nome_condominio")\
["nome_condominio"].to_list()

['2300 RIO DE JANEIRO',
 'ADMINISTRACAO DE COMPOSSUIDORES DO PROPRIO NACIONAL RESIDENCIAL EDIFICIO GENERAL ANTONIO BANDEIRA',
 'AIMORES CONDOMINIO DO EDIFICIO AIMORES',
 'ALENQUER ALCOE RESIDENCE',
 'ALFA CONDOMINIO EMPRESARIAL',
 'ALMA RESIDENCE',
 'ALTA VISTA DO PALMARES RESIDENCIAL',
 'ALTO GUTIERREZ CONDOMINIO BOUTIQUE',
 'ALTO HORIZONTE RESIDENCIAL',
 'APART HOTEL MAURILIO LAGES',
 'APARTHOTEL MAURILIO LAGES',
 'ASSOC DE MORADORES DO FAZENDA DA SERRA AMFS',
 'ASSOC.PROP.APTOS BLB COND.CONJ.HAB.DR.RODRIGO M.FRANCO',
 'ASSOCIACAO CONDOMINIO RESIDENCIAL PARQUET',
 'ASSOCIACAO CONDOMINIO RESIDENCIAL PARQUET',
 'ASSOCIACAO PROPRIETARIOS APTS BL B CONDOMINIO EDIFICIO CONJ. HAB. DR RODRIGO MELO FRANCO',
 'BE EASY STUDIOS RIVA',
 'BEATRIZ SIMAO RESIDENCE',
 'BELLA TOSCANA',
 'BELLAGIO ALCOE RESIDENCE',
 'BETANIA PARK RESIDENCIAS',
 'BH SQUARE CENTER',
 'BHDECOR',
 'BL II COND RESIDENCIAL ROSA ANDRADE SILVA',
 'BL III COND RESIDENCIAL ROSA ANDRADE SILVA',
 'BL IV COND RESIDENCIAL ROSA ANDRADE SILVA',
 'BLOCO 03 DO RESIDENCIAL KOLPING',
 'BLOCO II DO RESIDENCIAL KOLPING',
 'BLOCO IX DO CONJUNTO CIDADE NOVA',
 'BLOOMING BELVEDERE',
 'BRICKELL',
 'BRIZZE ESTORIL',
 'BURITIS RESIDENCE',
 'BURITIS STUDIO RESIDENCE',
 'C0NDOMINIO DO EDIFICIO VERA LUCIA LEMOS SANTOS',
 'C0NDOMINIO EDIFICIO WILDE LACERDA',
 'CAICARA FLATS',
 'CASTELO DE WINDSOR RESIDENCE',
 'CCONDOMINIO DO EDIFICIO ALEXANDRE',
 'CDONDOMINIO DO EDIFICIO CIRO PONI',
 'CENTRO ADMINISTRATIVO VALDIR MELGACO',
 'CENTRO COMERCIAL ADELAIDE',
 'CENTRO COMERCIAL BARAO',
 'CENTRO COMERCIAL CIDADE NOVA',
 'CENTRO COMERCIAL DBA VENDA NOVA',
 'CENTRO COMERCIAL DONATELLI',
 'CENTRO COMERCIAL DUQUE DE CAXIAS',
 'CENTRO COMERCIAL MANHATTAN',
 'CENTRO COMERCIAL MARIO WERNECK 2652',
 'CENTRO COMERCIAL PORTAL DA FLORESTA',
 'CENTRO EMPRESARIAL BETANIA',
 'CENTRO EMPRESARIAL CRISTIANO MACHADO',
 'CENTRO EMPRESARIAL ESTORIL',
 'CENTRO EMPRESARIAL GERSON DIAS',
 'CENTRO EMPRESARIAL HELIO ANTONINI',
 'CENTRO EMPRESARIAL LUIZ MAYRINK NETTO',
 'CENTRO EMPRESARIAL MARIO WERNECK',
 'CENTRO EMPRESARIAL OLIVEIRA',
 'CENTRO EMPRESARIAL RAJA GABAGLIA',
 'CENTRO EMPRESARIAL SANTA JULIANA',
 'CENTRO EMPRESARIAL SAO PEDRO',
 'CITTA PAMPULHA LAGOA',
 'CNDOMINIO DO EDICIO JOSE RODRIGUES',
 'CNDOMINIO DO EDIFICIO MANGABEIRA',
 'CNDOMINIO DO EFIDICIO ILHA BELA',
 'CODOMINIO DO ED. YOLANDA BOTELHO',
 'CODOMINIO DO EDFICIO LUANA',
 'CODOMINIO DO EDFICIO STENDHAL',
 'CODOMINIO DO EDIFICIO ANA LUCIA',
 'CODOMINIO DO EDIFICIO BARBARA LAMAS',
 'CODOMINIO DO EDIFICIO FLORIDA',
 'CODOMINIO DO EDIFICIO GOLDEN GARDEN',
 'CODOMINIO DO EDIFICIO ISA MARIA',
 'CODOMINIO DO EDIFICIO SANTORINI',
 'CODOMINIO DO EDIFICIO TOPAZIO IMPERIAL',
 'CODOMINIO DO EDIFICIO VILLE SAINT MARIENNE',
 'CODOMINIO DO RESIDENCIAL PALERMO',
 'CODOMINIO EDIFICIO CASSIO ANTONIO GONZAGA',
 'CODOMINIO EDIFICIO COELHO NETO',
 'CODOMINIO EDIFICIO GARDEN',
 'CODOMINIO MARIA QUITERIA MARIA ORTIZ',
 'CODOMINIO RESIDENCIAL COQUEIROS II',
 'COMDIMINIO DO EDIFICIO GUTIERREZ TRADE CENTER',
 'COMDOMINIO DO CENTRO COMERCIAL SION',
 'COMDOMINIO DO EDIFICIO CENTER SHOP',
 'COMDOMINIO DO EDIFICIO CLAUDIA',
 'COMDOMINIO DO EDIFICIO ESMERALDAS',
 'COMDOMINIO DO EDIFICIO FRANCISCO DE ALBUQUERQUE R BESSA',
 'COMDOMINIO DO EDIFICIO MARCELO MANSUR',
 'COMDOMINIO DO EDIFICIO MORADA REAL',
 'COMDOMINIO DO EDIFICIO OLIMPIA',
 'COMDOMINIO DO EDIFICIO ROMA',
 'COMDOMINIO DO EDIFICIO SAINT ETIENNE',
 'COMERCIAL SANT ANGELO',
 'COMERCIAL TERESA CRISTINA',
 'COMPLEXO VISTAS DO HORIZONTE',
 'COMPLEXO VISTAS DO HORIZONTE',
 'CON RES SANTA HELENA BLOCO A1',
 'CONCOMINIO DO EDIFICIO ANA AMELIA',
 'CONCOMINIO DO EDIFICIO CARLOS GOMES',
 'CONCOMINIO JARDIM DAS TUTERIAS',
 'COND CENTRO SOCIAL IPIRANGA',
 'COND CONJ HABITACIONAL HENRIQUE S ARAUJO BLOCO B I',
 'COND CONJ HABITACIONAL HENRIQUE S ARAUJO BLOCO BI',
 'COND DO CENTRO EMPRESARIAL SAO SEBASTIAO',
 'COND DO CONJ HABITACIONAL DR RODRIGO DE MELLO FRANCO',
 'COND DO CONJ HABITACIONAL PRESIDENTE CASTELO BRANCO',
 'COND DO ED JOSE PORFIRIO BOTELHO',
 'COND DO ED MAISON DE CHARTRES M DORLEANS E M DANGERS',
 'COND DO EDIF.JOSE MAURILIO DUARTE BRETAS',
 'COND DO EDIFICIO ANA PAULA',
 'COND DO EDIFICIO ATHENAS',
 'COND DO EDIFICIO AUGUSTO I',
 'COND DO EDIFICIO CAETANO DE AZEREDO',
 'COND DO EDIFICIO CENTRO EMPRESARIAL GERALDO MANSUR',
 'COND DO EDIFICIO ERICA ROLIM',
 'COND DO EDIFICIO IVNA',
 'COND DO EDIFICIO MONET',
 'COND DO EDIFICIO RESIDENCIAL SALINAS',
 'COND DO EDIFICIO RICARDO ALEIXO QUITES',
 'COND DO EDIFICIO SAINT LAURENT',
 'COND DO EDIFICIO SUZANA',
 'COND DO RES ABADIA',
 'COND DO RES BOSQUE DE SAO FRANCISCO I',
 'COND DO RES BOSQUE DE SAO FRANCISCO II',
 'COND DO RES BOSQUE DE SAO FRANCISCO II',
 'COND DO RESID. DOLOMITA',
 'COND DOS EDIFICIOS BRASILIA/CABO FRIO/MARAJO/M CLAROS',
 'COND DOS EDIFICIOS BRASILIACABO FRIOMARAJOM CLAROS',
 'COND ED ENG MARCUS DE SOUZA CASTILHO',
 'COND ED MARIA JOSINA DE OLIVEIRA',
 'COND ED RESIDENCIAL SANTA TEREZA',
 'COND EDF JOSE LUIZ BORGES HORTA',
 'COND EDIF BARROS RIBEIRO',
 'COND EDIF SEDE SIND TRAB IND MET MEC M ELET BH/CONTAGEM',
 'COND EDIF SEDE SIND TRAB IND MET MEC M ELET BHCONTAGEM',
 'COND EDIFICIO MARIA MADALENA ROCHA BRUM',
 'COND RESIDENCIAL SOLAR DO BARREIRO',
 'COND. BL.DA QUADRA 5 DO CONJ. HABITACIONAL SERRA VERDE',
 'COND. CONJ. HAB. HENRIQUE SILV ARAUJO',
 'COND. DO ED. DELANE',
 'COND. DO EDIFICIO DUKE ELLINGTON',
 'COND. DO EDIFICIO GISALVA FONSECA BARTOLOMEU',
 'COND. DO EDIFICIO HARVARD',
 'COND. DO EDIFICIO IVNA',
 'COND. DO EDIFICIO SAN LORENZO',
 'COND. DO PARQUE WINDSOR ED. MAURINO DE ARAUJO FERREIRA',
 'COND. DO. EDIFICIO SAN DIEGO CONVENTION FLAT',
 'COND. ED VILLAGIO CASTELLI',
 'COND. ED. ADELAIDE SANTIAGO',
 'COND. ED. ADRIANA',
 'COND. ED. AGUIDA TOZZI MACHADO',
 'COND. ED. ALCANTARA',
 'COND. ED. ALFA',
 'COND. ED. ALTINA LOBO',
 'COND. ED. AMANDA JULIANA',
 'COND. ED. ANA LUIZA',
 'COND. ED. ATLANTA',
 'COND. ED. BELA VISTA',
 'COND. ED. BELLA VITA STUDIO',
 'COND. ED. CAETANO VASCONCELOS',
 'COND. ED. CAIO CESAR',
 'COND. ED. CAMBRIDGE',
 'COND. ED. CARMEN',
 'COND. ED. CASSIA',
 'COND. ED. CEDRO',
 'COND. ED. CHOPPIN',
 'COND. ED. CHRISTOVAM PINHO',
 'COND. ED. CILIOMAR',
 'COND. ED. CONJUNTO CAPITOLIO',
 'COND. ED. COSTA SENNA',
 'COND. ED. DEMIEN II',
 'COND. ED. DOM DIEGO RUIZ',
 'COND. ED. DON ANGELO RONCALLI',
 'COND. ED. DON BOSCO',
 'COND. ED. DON FELIPE AUGUSTUS',
 'COND. ED. DONA ROSA',
 'COND. ED. DONA ZORAIDA',
 'COND. ED. DR. DOMINGOS H. GUSMAO',
 'COND. ED. DUQUE DE BRAGANCA',
 'COND. ED. DUQUE DE FIRENZE',
 'COND. ED. DUQUE DE VERSALHES',
 'COND. ED. EDSON RANGEL PROENCA',
 'COND. ED. ELIZABETH CIBELE',
 'COND. ED. ELZA DA SILVA CARMO',
 'COND. ED. EMILIA',
 'COND. ED. ERIKA TAVARES',
 'COND. ED. ESTEFANIA',
 'COND. ED. ESTER FERREIRA LUCIO',
 'COND. ED. ETELVINO VIEIRA COELHO',
 'COND. ED. FELIPE AUGUSTO II',
 'COND. ED. FLAVIA DE ALMEIDA SANTOS',
 'COND. ED. FLORENCA',
 'COND. ED. FORMATO II',
 'COND. ED. FRANCISCO GARCIA AZEVEDO',
 'COND. ED. GABRIELA',
 'COND. ED. GEORGETTE',
 'COND. ED. GRACY',
 'COND. ED. H.V.C.',
 'COND. ED. HONORIO DE PAIVA ABREU',
 'COND. ED. HUDSON CENTER',
 'COND. ED. ILE DE LA CITE',
 'COND. ED. INACIO MARIANO LANA',
 'COND. ED. IRENE',
 'COND. ED. ISABELA',
 'COND. ED. ITAGUARA',
 'COND. ED. ITALIA',
 'COND. ED. JACQUELINE',
 'COND. ED. JARDIM AMERICA',
 'COND. ED. JARDIM DE TIVOLI',
 'COND. ED. JEAN WERNER',
 'COND. ED. JOAO DE ALMEIDA',
 'COND. ED. JOSE MARCOLINI',
 'COND. ED. JOSE VALENTIM',
 'COND. ED. JULIANA',
 'COND. ED. JULIANNE',
 'COND. ED. LA PLATA',
 'COND. ED. LA ROCHELLE',
 'COND. ED. LELIA',
 'COND. ED. LILIAN DE ALMEIDA',
 'COND. ED. LIRIO',
 'COND. ED. LORD CROMWELL',
 'COND. ED. LUCAS MARTINS',
 'COND. ED. LUCY',
 'COND. ED. LUIZ FABIO',
 'COND. ED. MAISON STEPHANIE',
 'COND. ED. MARIA DA GLORIA',
 'COND. ED. MARIA HELENA',
 'COND. ED. MARIA MATTOS DE CASTRO BLOCOS C E D',
 'COND. ED. MARIZA FRAGA',
 'COND. ED. MATIAS BARBOSA',
 'COND. ED. MINAS GERAIS',
 'COND. ED. MIRAIA',
 'COND. ED. MONTE SANTO',
 'COND. ED. MONTES CLAROS',
 'COND. ED. OTAVIO ANDRADE',
 'COND. ED. OTAVIO MAFIA GOMES',
 'COND. ED. PALAZZO OLIVIERI',
 'COND. ED. PARC BELLE VUE',
 'COND. ED. PARC DES MONTAGNES',
 'COND. ED. PARIS',
 'COND. ED. PASSARGADA',
 'COND. ED. PEDRO TAVARES GONTIJO',
 'COND. ED. PORTOBELLO',
 'COND. ED. PRINCIPE DAS MARES',
 'COND. ED. PROF. ADYR ROCHA',
 'COND. ED. PROF. JOSE NARDELLI',
 'COND. ED. RACHEL PENA',
 'COND. ED. REGINA NOGUEIRA',
 'COND. ED. RENATA',
 'COND. ED. RENE RODIN',
 'COND. ED. RESD. MONTE CARLO',
 'COND. ED. RESD. MONTE CARLO',
 'COND. ED. RESID. RECANTO DA PITANGUEIRA',
 'COND. ED. RESIDENCIAL BASILEA',
 'COND. ED. RESIDENCIAL MONTES CLAROS',
 'COND. ED. RIO LOIRE',
 'COND. ED. RIO TEJO',
 'COND. ED. ROBERTAO',
 'COND. ED. ROSANA MELLO DA FONSECA',
 'COND. ED. SAINT LAURENT',
 'COND. ED. SAINT PAULIA',
 'COND. ED. SAN LORENZO',
 'COND. ED. SANTA ISABELLA',
 'COND. ED. SANTA LUCIA',
 'COND. ED. SANTA MARGHERITA',
 'COND. ED. SANTA MONICA',
 'COND. ED. SANTA RITA',
 'COND. ED. SANTINA',
 'COND. ED. SAO LUIZ',
 'COND. ED. SAO PEDRO VILLAGE',
 'COND. ED. SAVASSI TOP CENTER',
 'COND. ED. SEBASTIAO MARQUES FERNANDES',
 'COND. ED. SERRA MORENA',
 'COND. ED. SHOPPING CENTER TRANSITO LIVRE',
 'COND. ED. SILVANA',
 'COND. ED. SILVIA',
 'COND. ED. SILVIO PEREIRA',
 'COND. ED. SIMONE',
 'COND. ED. SOLAR DOS OLIVEIRA',
 'COND. ED. TAPAJOS E TOCANTINS',
 'COND. ED. TARSILA COSTA',
 'COND. ED. TOMAZ GONZAGA',
 'COND. ED. TOPAZIO',
 'COND. ED. TRIADES',
 'COND. ED. TROMBETAS',
 'COND. ED. ULISSES MARTINS ALVARENGA',
 'COND. ED. VALE DO SOL',
 'COND. ED. VALE VERDE',
 'COND. ED. VALERIA',
 'COND. ED. VERONETTI',
 'COND. ED. VILLA TORLONIA',
 'COND. ED. VILLE DE LOIRE',
 'COND. ED. VIP',
 'COND. ED. VITORIA',
 'COND. ED. VIVENDAS DA MATA',
 'COND. ED. VIVI BOURDOT',
 'COND. ED. VIVIAN NARA',
 'COND. ED. WALDEMAR HORTMANN',
 'COND. ED. WILLIAN DANIEL',
 'COND. ED. ZAIRA PACHECO',
 'COND. ED.JARDIM GUTIERREZ',
 'COND. EDF. MADRID',
 'COND. EDIF. MARIA FANTINI DE OLIVEIRA',
 'COND. EDIF. MARTHA CARDOSO DE BARROS',
 'COND. EDIF. RESIDENCIAL SAINT MORITZ',
 'COND. EDIFICIO AVENIDA',
 'COND. EDIFICIO BELO HORIZONTE',
 'COND. EDIFICIO JONATHAN',
 'COND. EDIFICIO PIGNATARO',
 'COND. EDIFICIO WOJTYLA',
 'COND. KALF CENTER',
 'COND. RES. RAPHAEL TUBERTINI',
 'COND. RESIDENCIAL BELVEDERE',
 'COND. RESIDENCIAL DEL REI BLC1 CONJ. HAB.CALIFORNIA II',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL SERRA VERDE III ED. SOLAR DOS ANJOS',
 'COND. RESIDENCIAL VILLAGE SAO PAULO',
 'COND.BL DA QUADRA 5 DO CONJ. HABITACIONAL SERRA VERDE',
 'COND.DO CONJ. HAB.RESIDENCIAL HELIOPOLISBLOCO 225',
 'COND.ED. DANTE MALAGUTI',
 'COND.ED. DONA CARMEM',
 'COND.ED. GUIGNARD',
 'COND.ED. MONTE BLANCO',
 'COND.ED.BELVEDERE II',
 'COND.ED.PORTAL DO ESTORIL',
 'COND.EDFICIO BLOCO 007',
 'COND.EDIFICIO MARGARETH QUEIROZ WENCESLAU',
 'CONDIMINIO DO EDIFICIO BARBARA PORTES',
 'CONDIMINIO DO EDIFICIO RESIDENCIAL CORDOBA',
 'CONDIMINIO EDIFICIO FLOR DE LIZ',
 'CONDIMINIO RESIDENCIAL HONDURAS BLOCO 02',
 'CONDMINIO DO EDIFICIO ANA MARIA',
 'CONDMINIO DO EDIFICIO DO CARMO',
 'CONDMINIO DO EDIFICIO DONA CONSTANCIA',
 'CONDMINIO DO EDIFICIO MARDEL PLATA',
 'CONDMINIO DO EDIFICIO MARIA FERNANDA',
 'CONDOIMINIO DO EDIFICIO JULIANA',
 'CONDOIMINIO DO EDIFICIO SOLAR DOS ROUXINOIS',
 'CONDOMIINIO EDIFICIO GERALDO FONSECA',
 'CONDOMIIO DO EDIFICIO DEBORA',
 'CONDOMIIO DO EDIFICIO EMILIA CAMPOS',
 'CONDOMIMIO DO EDFICIO SAMUARA',
 'CONDOMIMIO DO EDIFICIO GARDENPARTY',
 'CONDOMIMIO DO EDIFICIO LIENZ',
 'CONDOMIMIO DO EDIFICIO RESIDENCIAL MAR EGEU',
 'CONDOMIMIO EDIFICIO RENATA',
 'CONDOMIMNIO DO EDIFICIO LUCIANNE',
 'CONDOMIN IO DO EDIFICIO BELLAGIO',
 'CONDOMIN IO DO EDIFICIO RESIDENCIAL CASTELO DAS ESCUMILHAS',
 'CONDOMINI0 DO EDIFICIO BORGES MIRANDA',
 'CONDOMINI0 DO EDIFICIO DOM JOAO GABRIEL',
 'CONDOMINI0 DO EDIFICIO KYRA WALLER',
 'CONDOMINIIO DO CONJUNTO RESIDENCIAL LUCIANNE',
 'CONDOMINIIO EDIFICIO MIKHAIL SAFAR',
 'CONDOMININIO DO EDIFICIO BERILO',
 'CONDOMININIO DO EDIFICIO JOAQUIM CANDIDO DE ANDRADE',
 'CONDOMININO DO EDIFICIO FREDERICO',
 'CONDOMININO DO EDIFICIO LEOPOLDO MIRANDA',
 'CONDOMININO DO EDIFICIO RESIDENCIAL TORRE DI AGUIA',
 'CONDOMINIO 4 CONJ HABIT CALIFORNIA',
 'CONDOMINIO ACAPULCO/CANCUN',
 'CONDOMINIO ACAPULCOCANCUN',
 'CONDOMINIO ADELINA LUSTOSA',
 'CONDOMINIO ADRIANA',
 'CONDOMINIO ADRIANE DRUMOND ALMEIDA',
 'CONDOMINIO AGATA',
 'CONDOMINIO AGATA STREET MALL PALMARES',
 'CONDOMINIO AGENY FERNANDES MACHADO',
 'CONDOMINIO AGOSTINHO GONZAGA PIRES',
 'CONDOMINIO AGRIPINA',
 'CONDOMINIO AGUEDA LUTTERBACH',
 'CONDOMINIO AGULHAS NEGRAS',
 'CONDOMINIO AIDA FURST SANTIAGO',
 'CONDOMINIO AIMORES MORADIAS',
 'CONDOMINIO ALBATROZ III',
 'CONDOMINIO ALDA MENDONCA',
 'CONDOMINIO ALENCAR GONCALVES DE REZENDE',
 'CONDOMINIO ALFA',
 'CONDOMINIO ALFREDO WARDI',
 'CONDOMINIO ALICERCE CASTOR VDM',
 'CONDOMINIO ALICERCECASTORVDM',
 'CONDOMINIO ALIPIO DE MELO',
 'CONDOMINIO ALLEGRO 530',
 'CONDOMINIO ALPES SUICOS',
 'CONDOMINIO ALPES SUICOS',
 'CONDOMINIO ALTA VISTA RESIDENCE',
 'CONDOMINIO ALTEROSA MALL',
 'CONDOMINIO ALTO BOA VISTA RESIDENCIAL',
 'CONDOMINIO ALTO DOS COQUEIROS',
 'CONDOMINIO ALTO GUANDU',
 'CONDOMINIO ALTO RIVIERA RESIDENCIAL',
 'CONDOMINIO ALVARO CARDOSO',
 'CONDOMINIO AMALIA NATALI GERVASIO',
 'CONDOMINIO AMARANTES',
 'CONDOMINIO AMAZONAS',
 'CONDOMINIO AMAZONAS',
 'CONDOMINIO AMELIA PASSOS',
 'CONDOMINIO AMERICO VESPUCIO',
 'CONDOMINIO ANA CAROLINA',
 'CONDOMINIO ANA SALES',
 'CONDOMINIO ANGELA XIMENES',
 'CONDOMINIO ANGELINA ALBERTI LOPES',
 'CONDOMINIO ANGELINA NARDELLI',
 'CONDOMINIO ANITA FERNANDES',
 'CONDOMINIO ANNA DASSUMPCAO',
 'CONDOMINIO ANTARES EDIFICIO',
 'CONDOMINIO ANTONIO AVENDANHA SOBRINHO',
 'CONDOMINIO ANTONIO CANDIDO RIBEIRO',
 'CONDOMINIO ANTONIO CARLOS',
 'CONDOMINIO ANTONIO DAMASCENO JUNIOR',
 'CONDOMINIO ANTONIO DAMASCENO JUNIOR',
 'CONDOMINIO ANTONIO MARCOS',
 'CONDOMINIO ANTONIO RODRIGUES DE LIMA',
 'CONDOMINIO AQUA CLUBE RESIDENCIAL',
 'CONDOMINIO ARAGUAIA',
 'CONDOMINIO ARAUJO DE CARVALHO',
 'CONDOMINIO ARCA',
 'CONDOMINIO ARCA',
 'CONDOMINIO ARES DO PRADO',
 'CONDOMINIO ARGOS EDIFICIO',
 'CONDOMINIO AROLDO RODRIGUES',
 'CONDOMINIO ARPOADOR',
 'CONDOMINIO ARTHUR FERREIRA',
 'CONDOMINIO ASPEN',
 'CONDOMINIO ASPEN HILL',
 'CONDOMINIO ASTRUBAL TEIXEIRA DE SOUZA',
 'CONDOMINIO ASTURIAS',
 'CONDOMINIO ATALIBA SALES',
 'CONDOMINIO ATARI XX',
 'CONDOMINIO AUGUSTE RODIN',
 'CONDOMINIO AVILA',
 'CONDOMINIO BALCONY RESIDENCE',
 'CONDOMINIO BARAO DE COROMANDEL',
 'CONDOMINIO BARBONAGLIA',
 'CONDOMINIO BARCELONA RESIDENCIAL',
 'CONDOMINIO BARCELOS',
 'CONDOMINIO BEATRIZ',
 'CONDOMINIO BEATRIZ RODRIGUES PRADO',
 'CONDOMINIO BELA VISTA',
 'CONDOMINIO BELA VISTA',
 'CONDOMINIO BELLA VERONA',
 'CONDOMINIO BELLA VITA',
 'CONDOMINIO BELLE VIE RESIDENCE',
 'CONDOMINIO BELLE VILLAGE',
 'CONDOMINIO BELO HORIZONTE',
 'CONDOMINIO BELO HORIZONTE',
 'CONDOMINIO BELVEDERE PARK',
 'CONDOMINIO BENJAMIM SOARES',
 'CONDOMINIO BERNARDES DE ASSIS',
 'CONDOMINIO BEVERLY HILLS',
 'CONDOMINIO BH OUTLET PLUS',
 'CONDOMINIO BOA ESPERANCA',
 'CONDOMINIO BOLONHA',
 'CONDOMINIO BONJARDIM DA SERRA',
 'CONDOMINIO BOSQUE DAS MANGUEIRAS',
 'CONDOMINIO BOSQUE DO MOSTEIRO',
 'CONDOMINIO BOSQUE DO MOSTEIRO',
 'CONDOMINIO BOSSA NOVA PARK',
 'CONDOMINIO BOULEVARD ESPLANADA',
 'CONDOMINIO BOULEVARD ESPLANADA',
 'CONDOMINIO BRAGANCA',
 'CONDOMINIO BRENO',
 'CONDOMINIO BRISA DO LUXEMBURGO',
 'CONDOMINIO BRISA STREET MALL E BRISA FLEMING',
 'CONDOMINIO BRUGES',
 'CONDOMINIO CACHOEIRA DO CAMPO EDIF. BERNARDO MENDES RIBEIRO',
 'CONDOMINIO CACHOEIRA DO CAMPO EDIFICIO MOACIR MENDES MORATO',
 'CONDOMINIO CACHOEIRA DOURADA',
 'CONDOMINIO CAMARGO EDIFICIO CANADA',
 'CONDOMINIO CAMARGOS EDIFICIO BRASIL',
 'CONDOMINIO CAMARGOS EDIFICIO GRECIA',
 'CONDOMINIO CAMPOS ALTOS II',
 'CONDOMINIO CAMPOS CUNHA',
 'CONDOMINIO CANAA',
 'CONDOMINIO CANOAS PARK RESIDENCIAS',
 'CONDOMINIO CARLOS GOMES',
 'CONDOMINIO CARLOS HENRIQUE',
 'CONDOMINIO CARMELITA TOLEDO',
 'CONDOMINIO CAROLINA MATOS',
 'CONDOMINIO CASA MAIOR',
 'CONDOMINIO CASAS BELA VISTA',
 'CONDOMINIO CASAS BELA VISTA',
 'CONDOMINIO CASPOL',
 'CONDOMINIO CASTANHA DO PARA',
 'CONDOMINIO CASTANHEIRA',
 'CONDOMINIO CASTANHEIRAS EDIFICIO MOGNO',
 'CONDOMINIO CASTANHEIRAS EDIFICIO MOGNO',
 'CONDOMINIO CELEIRO MALL 1200',
 'CONDOMINIO CELESTE IMPERIAL',
 'CONDOMINIO CELMA FIGUEIREDO',
 'CONDOMINIO CELSO LOBO DE REZENDE',
 'CONDOMINIO CENTER CEU AZUL',
 'CONDOMINIO CENTER SAO BENTO LTDA',
 'CONDOMINIO CENTRAL PARK',
 'CONDOMINIO CENTRAL PARK SHOPPING',
 'CONDOMINIO CENTRAL PARK SHOPPING E RESIDENCES',
 'CONDOMINIO CENTRAL PARK SHOPPING E RESIDENCES',
 'CONDOMINIO CENTRO COMERCIAL AGGEO PIO',
 'CONDOMINIO CENTRO COMERCIAL CARVALHO ALMEIDA',
 'CONDOMINIO CENTRO COMERCIAL CASTELO DE VIENA',
 'CONDOMINIO CENTRO COMERCIAL INCONFIDENTES',
 'CONDOMINIO CENTRO COMERCIAL JORGE LIMA',
 'CONDOMINIO CENTRO COMERCIAL MARIALICE F. MACHADO',
 'CONDOMINIO CENTRO COMERCIAL MARIALICE F. MACHADO',
 'CONDOMINIO CENTRO COMERCIAL PARQUE BURITIS',
 'CONDOMINIO CENTRO COMERCIAL SKINA DA CONVENIENCIA',
 'CONDOMINIO CENTRO DE ESPECIALIDADES MEDICAS CEM',
 'CONDOMINIO CENTRO DE ESPECIALIDADES MEDICASCEM',
 'CONDOMINIO CENTRO DE SAUDE, ESPORTE E LAZER',
 'CONDOMINIO CENTRO EMPRESARIAL ASSIS CHATEAUBRIAND',
 'CONDOMINIO CENTRO EMPRESARIAL BARRO PRETO',
 'CONDOMINIO CENTRO EMPRESARIAL DARWEN FRANCISCO',
 'CONDOMINIO CENTRO EMPRESARIAL E COMERCIAL PAMPULHA',
 'CONDOMINIO CENTRO EMPRESARIAL GERSON DIAS',
 'CONDOMINIO CENTRO EMPRESARIAL MED MAX',
 'CONDOMINIO CENTRO EMPRESARIAL MIMI LIBORIO',
 'CONDOMINIO CENTRO EMPRESARIAL PARQUE BURITIS',
 'CONDOMINIO CENTURY RESIDENCE SERVICE',
 'CONDOMINIO CESARIO DE BARROS',
 'CONDOMINIO CHATEAU AMBOISE',
 'CONDOMINIO CHATEAU AMBOISE',
 'CONDOMINIO CIDADE NOVA',
 'CONDOMINIO CIDADE NOVA',
 'CONDOMINIO CIDADE NOVA',
 'CONDOMINIO CIDADE NOVA',
 'CONDOMINIO CIDADE NOVA BLOCO 10',
 'CONDOMINIO CIDADE NOVA BLOCO 3',
 'CONDOMINIO CIDADES MINEIRAS',
 'CONDOMINIO CIDI',
 'CONDOMINIO CITTA PAMPULHA CLUBE',
 'CONDOMINIO CITTA PAMPULHA IATE',
 'CONDOMINIO CLAUDE MONET',
 'CONDOMINIO CLAUDIA CAETANO',
 'CONDOMINIO CLAUDIO JOSE NEVES',
 'CONDOMINIO CLELIA DO EDIFICIO MARIANGELA',
 'CONDOMINIO CLELIA DO EDIFICO MARIANGELA',
 'CONDOMINIO CLOVIS SOARES DINIZ',
 'CONDOMINIO CLUBE DOS VINTE E OITO',
 'CONDOMINIO COMERCIAL BELVEDERE ONE',
 'CONDOMINIO COMERCIAL DO EDIFICIO BERGAMO',
 'CONDOMINIO COMERCIAL DO EDIFICIO DONA RAFAELA',
 'CONDOMINIO COMERCIAL DO EDIFICIO GASTAO FERREIRA DOS SANTOS',
 'CONDOMINIO COMERCIAL DO EDIFICIO PROFESSORA MARIA DE LOURDES RESENDE',
 'CONDOMINIO COMERCIAL DO EDIFICIO TODAY',
 'CONDOMINIO COMERCIAL FERNAO DIAS',
 'CONDOMINIO COMERCIAL FURTADO',
 'CONDOMINIO COMERCIAL ISABELLA',
 'CONDOMINIO COMERCIAL REAL CENTER',
 'CONDOMINIO COMERCIAL SILVEIRA CENTER',
 'CONDOMINIO CONDE DA COVILHA',
 'CONDOMINIO CONJ HAB HENRIQUE SILVA ARAUJO BLOCO A 3',
 'CONDOMINIO CONJ HABIT PAINEIRAS EDIF LEONARDO DVINCI',
 'CONDOMINIO CONJ HABITACIONAL RESID HELIOPOLISBLOCO 195',
 'CONDOMINIO CONJ RESIDENCIAL SARANDI II Q69 BLOCO 380',
 'CONDOMINIO CONJ. HABITACIONAL RESIDENCIAL HELIOPOLIS BL 195',
 'CONDOMINIO CONJ. HENRIQUE SILVA ARAUJO',
 'CONDOMINIO CONJ. RES. SERRA VERDE',
 'CONDOMINIO CONJ. RESID. SARANDI I EDIFICIO PORTAL DA TERRA',
 'CONDOMINIO CONJUNTO ANCHIETA BLOCO B',
 'CONDOMINIO CONJUNTO GUTIERREZ',
 'CONDOMINIO CONJUNTO HABITACIONAL CALIFORNIA',
 'CONDOMINIO CONJUNTO HABITACIONAL CASTELO I',
 'CONDOMINIO CONJUNTO HABITACIONAL DR. FABIO SOARE CAMPOS',
 'CONDOMINIO CONJUNTO HABITACIONAL HENRIQUE SILVA ARAUJO',
 'CONDOMINIO CONJUNTO HABITACIONAL HENRIQUE SILVA ARAUJO',
 'CONDOMINIO CONJUNTO HABITACIONAL HENRIQUE SILVA ARAUJO',

In [289]:
df_atividades_economicas[["natureza_juridica", "ind_simples", "ind_mei"]].value_counts().reset_index()\
.assign(ind = lambda df: df["ind_simples"] + df["ind_mei"])\
.assign(soma = lambda df: df.groupby("natureza_juridica")["count"].transform("sum"))\
.pivot_table(index = ["natureza_juridica", "soma"], columns = ["ind"], values = "count")\
.fillna("")\
.reset_index()\
.sort_values("soma", ascending = False)\
.loc[:60]

ind,natureza_juridica,soma,NN,SN,SS
18,EMPRESÁRIO (INDIVIDUAL),578526,13270.0,35484.0,529772.0
48,SOCIEDADE EMPRESÁRIA LIMITADA,309694,139369.0,168129.0,2196.0
7,CONDOMÍNIO EDILÍCIO,26219,26217.0,2.0,
51,SOCIEDADE SIMPLES LIMITADA,20828,11919.0,8909.0,
13,EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITAD...,20668,7464.0,13204.0,
43,SOCIEDADE ANÔNIMA FECHADA,12853,12820.0,33.0,
0,ASSOCIAÇÃO PRIVADA,10620,10615.0,5.0,
53,SOCIEDADE UNIPESSOAL DE ADVOGADOS,6037,1887.0,4148.0,2.0
52,SOCIEDADE SIMPLES PURA,5033,2024.0,3009.0,
45,SOCIEDADE EM CONTA DE PARTICIPAÇÃO,3580,3580.0,,
36,ORGANIZAÇÃO RELIGIOSA,2653,2653.0,,
9,CONSÓRCIO DE SOCIEDADES,1943,1943.0,,
42,SOCIEDADE ANÔNIMA ABERTA,1878,1878.0,,
14,EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITAD...,1596,759.0,837.0,
11,COOPERATIVA,763,763.0,,
20,ENTIDADE SINDICAL,728,728.0,,
23,FUNDAÇÃO PRIVADA,403,403.0,,
34,MUNICÍPIO,373,373.0,,
17,EMPRESA SIMPLES DE INOVAÇÃO - INOVA SIMPLES,352,294.0,58.0,
44,SOCIEDADE DE ECONOMIA MISTA,282,282.0,,
16,EMPRESA PÚBLICA,245,245.0,,
62,ÓRGÃO PÚBLICO DO PODER EXECUTIVO MUNICIPAL,186,186.0,,
2,AUTARQUIA FEDERAL,152,152.0,,
41,SERVIÇO SOCIAL AUTÔNOMO,139,139.0,,
60,ÓRGÃO PÚBLICO DO PODER EXECUTIVO ESTADUAL OU D...,137,136.0,1.0,

In [267]:
df_atividades_economicas\
.query("~natureza_juridica.str.contains('EMPRES.RIO \(INDIVIDUAL\)')")\
.query("ind_mei == 'S'")

,cnae_principal,descricao_cnae,cnae_secundarias,natureza_juridica,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,nome,nome_fantasia,cnpj,data_inicio_atividade,nome_regional,geometria,urlfile,ind_possui_alvara
index,,,,,,,,,,,,,,,,,,,,,,,
110395,4511102.0,"COMERCIO A VAREJO DE AUTOMOVEIS, CAMIONETAS E ...","4511101, 4511103, 4511104, 4511105, 4511106, 4...",SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"PORTA A PORTA, POSTOS MÓVEIS OU POR AMBULANTES",RUA,DOS AERONAUTAS,256,nan,LIBERDADE,MINUTO VEICULOS LTDA,DOMUS,21986528000151,10/05/2016,PAMPULHA,POINT (609230.784378778 7803808.99547387),20220601_atividade_economica.csv,nan
115525,7319002.0,PROMOCAO DE VENDAS,"4512901, 4930202, 8211300",SOCIEDADE EMPRESÁRIA LIMITADA,EMPRESA DE PEQUENO PORTE,10.0,S,S,UNIDADE PRODUTIVA,"INTERNET, TELEVENDAS",RUA,TELESCOPIO,407,nan,MIRAMAR,DIAS EMPREENDIMENTOS E TRANSPORTES LTDA,DIAS EMPREENDIMENTOS E REPRESENTACAO,26094347000134,02/09/2016,BARREIRO,POINT (603196.638605644 7788604.81976724),20220601_atividade_economica.csv,nan
125852,9602501.0,"CABELEIREIROS, MANICURE E PEDICURE",9602502,SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,PADRE JOSE ALVES,342,nan,SAO PAULO,SALAO JEITO JOVEM LTDA,SALAO JEITO JOVEM,26715726000102,14/12/2016,NORDESTE,POINT (612607.714941593 7802858.48336503),20220601_atividade_economica.csv,nan
172610,6821801.0,CORRETAGEM NA COMPRA E VENDA E AVALIAÇÃO DE IM...,6821802,SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ATIVIDADES DESENVOLVIDAS FORA DO ESTABELECIMEN...,AVE,ALVARES CABRAL,1162,APT 501,LOURDES,ALENE DUARTE CORRETORA LTDA,REMODELAR ESTETICA,26282896000132,13/06/2017,CENTRO-SUL,POINT (610399.547311648 7795946.96351472),20220601_atividade_economica.csv,nan
181542,5912099.0,"ATIVIDADES DE POS-PRODUCAO CINEMATOGRAFICA, DE...","1813001, 1813099, 1822999, 5811500, 5812301, 5...",SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"ESTABELECIMENTO FIXO, INTERNET",RUA,CORONEL FULGENCIO,428,APT 6,NOVO SAO LUCAS,PB IDEIAS SOLUCOES EM AUDIOVISUAL LTDA,PB IDEIAS,22796154000174,06/07/2015,CENTRO-SUL,POINT (613412.1168943 7796019.39871637),20220601_atividade_economica.csv,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993554,1091102.0,FABRICAÇÃO DE PRODUTOS DE PADARIA E CONFEITARI...,"1091102, 4721104, 5611203, 5620104",SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"INTERNET, PORTA A PORTA, POSTOS MÓVEIS OU POR ...",RUA,PARAIBA,281,nan,FUNCIONARIOS,DOCURAS DA FLAVINHA LTDA,DOCURAS DA FLAVINHA BH,55833484000141,07-07-2024,nan,POINT (611822.67 7796037.99),20251001_atividade_economica.csv,NÃO
993576,2599301.0,SERVIÇOS DE CONFECÇÃO DE ARMAÇÕES METÁLICAS PA...,2599301,SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,EM LOCAL FIXO FORA DE LOJA,RUA,SANTA MARIA,113,nan,VILA NOVA PARAISO,DG ARMACOES EM GERAL LTDA,nan,54816409000100,20-04-2024,nan,POINT (606126.42 7790580.25),20251001_atividade_economica.csv,NÃO
993584,7719599.0,LOCAÇÃO DE OUTROS MEIOS DE TRANSPORTE NÃO ESPE...,7719599,SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"CORREIO, EM LOCAL FIXO FORA DE LOJA, ESTABELEC...",RUA,IZABEL ALVES MARTINS,402,nan,SERRANO,JLL LOCACOES DE MEIOS DE TRANSPORTE LTDA,JLL LOCACOES,55167984000191,17-05-2024,nan,POINT (603548.77 7801340.83),20251001_atividade_economica.csv,NÃO
993585,4929904.0,ORGANIZAÇÃO DE EXCURSÕES EM VEÍCULOS RODOVIÁRI...,"4929904, 4930202, 5229001, 5229099, 5320202",SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"ESTABELECIMENTO FIXO, INTERNET, MÁQUINAS AUTOM...",RUA,DEUSDEDITH DE ASSIS,55,nan,DOM BOSCO,AGILIZA LOG TRANSPORTES LTDA,nan,54888460000127,25-04-2024,nan,POINT (604149.56 7796760.19),20251001_atividade_economica.csv,NÃO
993592,9313100.0,ATIVIDADES DE CONDICIONAMENTO FÍSICO,"8650004, 9313100",SOCIEDADE EMPRESÁRIA LIMITADA,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,MADRE PAULINA,305,nan,DIAMANTE,STUDIO DE PILATES E FISIOTERAPIA CAMILA NASCIM...,CAMILA OLIVEIRA,41170009000128,10-03-2021,nan,POINT (601247.55 7789680.96),20251001_atividade_economica.csv,SIM

In [178]:
xdf.query("tp_ == 'SS0'")

Empty DataFrame
Columns: [cnpj, nome, nome_fantasia, data_inicio_atividade, nome_regional, cnae_principal, cnae_secundarias, descricao_cnae, porte_empresa, area_utilizada, ind_simples, ind_mei, tipo_unidade, forma_atuacao, desc_logradouro, nome_logradouro, numero_imovel, complemento, nome_bairro, geometria, ind_id, tp_nome, tp_]
Index: []

In [179]:
df_empresarios_individuais\
.query("ind_id == 'SS0'")

,cnpj,nome,nome_fantasia,data_inicio_atividade,nome_regional,cnae_principal,cnae_secundarias,descricao_cnae,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,geometria,ind_id
index,,,,,,,,,,,,,,,,,,,,,
55,71046767000108,HELIO JOSE DOS PASSOS,nan,01/06/1993,OESTE,9521500.0,nan,REPARACAO E MANUTENCAO DE EQUIPAMENTOS ELETROE...,MICROEMPRESA - ME,69.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,TERESA CRISTINA,8000,nan,BAIRRO DAS INDUSTRIAS II,POINT (604832.714235935 7792733.44122486),SS0
77,70985205000159,ADEMIR SANTANA DA SILVA,CICE BALAS,01/04/1993,BARREIRO,4712100.0,"4713002, 4721104, 4789099","COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, CO...",MICROEMPRESA - ME,113.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,ERIDANO,245,LOJA 2,CARDOSO,POINT (603663.25825095 7788538.41657597),SS0
188,23962111000184,ANA R L BRAGA BITENCOURT CONFECCOES,BRAGA & BITENCOURT INDUSTRIA E COMERCIO DE CON...,01/03/1993,BARREIRO,1412602.0,1412603,"CONFECCAO, SOB MEDIDA, DE PECAS DO VESTUARIO, ...",MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CASTOR,147,SALA 01,MIRAMAR,POINT (603381.602157723 7788738.6632132),SS0
304,71077689000109,ELVECIO ALVES DE OLIVEIRA,CHAVEIRO GUARARAPES,01/06/1993,NOROESTE,9529102.0,8299703,CHAVEIROS,DEMAIS,20.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,GUARARAPES,1300,C,PINDORAMA,POINT (602776.994906018 7798403.63853863),SS0
372,65096224000194,ROSANGELA FERREIRA CAMPOS MACHADO - CALCADOS,SCARPE MODAS,18/02/1991,PAMPULHA,4782201.0,"4755502, 4781400, 4789099",COMERCIO VAREJISTA DE CALCADOS,MICROEMPRESA - ME,37.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,CORONEL JOSE DIAS BICALHO,1221,nan,SAO JOSE,POINT (607782.12181818 7803582.56055663),SS0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881290,28900665000170,M. A. DA SILVA FIRMINO,VISAO DE AGUIA COLCHOES,20-10-2017,nan,4754702.0,"4754701, 4754702, 4759899, 4781400, 4783101, 4...",COMERCIO VAREJISTA DE ARTIGOS DE COLCHOARIA,MICROEMPRESA - ME,18.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,RADIALISTA JUSCELINO SOUZA,310,nan,CEU AZUL,POINT (603987.99 7808607.97),SS0
893024,17020087000161,JOSE CARLOS RODRIGUES DOS SANTOS,nan,17-10-2012,nan,4520006.0,4520006,SERVICOS DE BORRACHARIA PARA VEICULOS AUTOMOTORES,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,RIBATEJO,110,nan,CACHOEIRINHA,POINT (609880.35 7801820.00),SS0
898729,31141084000107,DENILSON DE PAULA SOLUCOES EM EQUIPAMENTOS REC...,MVL SOLUCOES,07-08-2018,nan,3314710.0,"3314710, 7319003, 7721700",MANUTENCAO E REPARACAO DE MAQUINAS E EQUIPAMEN...,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,MÁQUINAS AUTOMÁTICAS,RUA,INDIRA GANDHI,133,nan,TUPI A,POINT (613024.10 7806591.46),SS0
902361,21926458000146,ADRIANA AMELIA SILVA,nan,24-02-2015,nan,4723700.0,"4712100, 4723700, 7729202",COMÉRCIO VAREJISTA DE BEBIDAS,MICROEMPRESA - ME,50.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,DOS COMANCHES,560,LETRA A,SANTA MONICA,POINT (606597.18 7807049.63),SS0
934238,31141084000107,DENILSON DE PAULA SOLUCOES EM EQUIPAMENTOS REC...,MVL SOLUCOES,07-08-2018,nan,3314710.0,"3314710, 7319003, 7721700",MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMEN...,MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,MÁQUINAS AUTOMÁTICAS,RUA,DOS IMBIRAS,10,LOJA A,FLORAMAR,POINT (611714.03 7805578.40),SS0

In [133]:
xdf.query("tp_ == 0")

Empty DataFrame
Columns: [cnpj, nome, nome_fantasia, data_inicio_atividade, nome_regional, cnae_principal, cnae_secundarias, descricao_cnae, porte_empresa, area_utilizada, ind_simples, ind_mei, tipo_unidade, forma_atuacao, desc_logradouro, nome_logradouro, numero_imovel, complemento, nome_bairro, geometria, ind_id, tp_nome, tp_]
Index: []

In [46]:
df_atividades_economicas\
.query("natureza_juridica.str.contains('EMPRES.RIO \(INDIVIDUAL\)')")

,cnae_principal,descricao_cnae,cnae_secundarias,natureza_juridica,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,nome,nome_fantasia,cnpj,data_inicio_atividade,nome_regional,geometria,urlfile,ind_possui_alvara
index,,,,,,,,,,,,,,,,,,,,,,,
27,7500100.0,ATIVIDADES VETERINÁRIAS EXERCIDAS EM CLÍNICAS ...,"4771704, 4789004, 4789099, 9609207, 9609208",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,55.0,S,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,ARTUR GUIMARAES,155,nan,SANTA CRUZ,MARCIO BRASIL ROCHA,nan,66477498000196,22/03/1993,NORDESTE,POINT (611354.775664121 7801545.91893658),20220601_atividade_economica.csv,nan
33,4724500.0,COMERCIO VAREJISTA DE HORTIFRUTIGRANJEIROS,"4712100, 5611203",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,81.0,S,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CIBIPURUNA,171,nan,MONTE AZUL,MANOEL ADUIRES DA SILVA,MANOEL ADUIRES DA SILVA,38462867000131,01/04/1990,NORTE,POINT (615915.892278689 7808531.04864468),20220601_atividade_economica.csv,nan
43,4520001.0,SERVICOS DE MANUTENCAO E REPARACAO MECANICA DE...,"4520002, 4520003, 4520004",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,150.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,DOUTOR BENJAMIM MOSS,319,nan,UNIAO,ROBSON SALES HENEDINO,nan,70986948000143,01/04/1993,NORDESTE,POINT (613033.200778877 7800638.00374008),20220601_atividade_economica.csv,nan
47,4772500.0,"COMERCIO VAREJISTA DE COSMETICOS, PRODUTOS DE ...","4721104, 4723700, 4789099, 5611203",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,20.0,S,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,JOSE BRANDAO,174,LOJA,BARREIRO,PAUL BLAHA,nan,68553478000182,01/12/1992,BARREIRO,POINT (603131.422191837 7790981.54869036),20220601_atividade_economica.csv,nan
55,9521500.0,REPARACAO E MANUTENCAO DE EQUIPAMENTOS ELETROE...,nan,EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,69.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,TERESA CRISTINA,8000,nan,BAIRRO DAS INDUSTRIAS II,HELIO JOSE DOS PASSOS,nan,71046767000108,01/06/1993,OESTE,POINT (604832.714235935 7792733.44122486),20220601_atividade_economica.csv,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536710,4781400.0,COMERCIO VAREJISTA DE ARTIGOS DO VESTUARIO E C...,"1412602, 4781400",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CASTIGLIANO,621,APT 104,PADRE EUSTAQUIO,36.766.918 JOANA ANGELICA SILVA DE SOUZA,JOANA ANGELICA EMPREEDIMENTOS,36766918000193,25-03-2020,nan,POINT (607217.55 7797321.52),20251103_atividade_economica.csv,NÃO
1536924,5620104.0,FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDER...,"5611203, 5620104, 9602501, 9602502",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"ESTABELECIMENTO FIXO, INTERNET",RUA,L,100,LOJA LOJA,CONJUNTO MINASCAIXA,37.087.365 ELISABETH FERNANDA GARCIA CARDOSO B...,LANCHES EXPRESS,37087365000105,07-05-2020,nan,POINT (609085.97 7809993.00),20251103_atividade_economica.csv,NÃO
1537457,4930202.0,"TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO...","4930201, 4930202, 4930204",EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"EM LOCAL FIXO FORA DE LOJA, ESTABELECIMENTO FI...",RUA,O ATENEU,19,CASA CS,ADEMAR MALDONADO,28.169.364 ANDREIA RODRIGUES CLARK CAMPOS,nan,28169364000119,27-01-2025,nan,POINT (601943.94 7790116.07),20251103_atividade_economica.csv,NÃO
1538609,8230001.0,"SERVICOS DE ORGANIZACAO DE FEIRAS, CONGRESSOS,...",8230001,EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,10.0,S,S,UNIDADE PRODUTIVA,"PORTA A PORTA, POSTOS MÓVEIS OU POR AMBULANTES",RUA,AMPARO DA SERRA,89,CASA,ARAGUAIA,59.282.548 PATRICIA DANIELLE NUNES FERREIRA DE...,nan,59282548000114,04-02-2025,nan,POINT (603962.17 7789312.37),20251103_atividade_economica.csv,NÃO
1538878,9602502.0,ATIVIDADES DE ESTÉTICA E OUTROS SERVIÇOS DE CU...,9602502,EMPRESÁRIO (INDIVIDUAL),MICROEMPRESA - ME,40.0,S,S,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,CRISTIANO MOREIRA SALES,150,SALA 509,ESTORIL,59.216.311 GABRIELA RAMOS ARAUJO,nan,59216311000135,31-01-2025,nan,POINT (609103.96 7791899.58),20251103_atividade_economica.csv,SIM

In [23]:
df_atividades_economicas["natureza_juridica"].value_counts()

natureza_juridica
EMPRESÁRIO (INDIVIDUAL)                                                     578526
SOCIEDADE EMPRESÁRIA LIMITADA                                               309694
CONDOMÍNIO EDILÍCIO                                                          26219
SOCIEDADE SIMPLES LIMITADA                                                   20828
EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA (DE NATUREZA EMPRESARIA)     20668
                                                                             ...
CANDIDATO A CARGO POLÍTICO ELETIVO                                               1
COMISSÃO DE CONCILIAÇÃO PRÉVIA                                                   1
COMUNIDADE INDÍGENA                                                              1
GRUPO DE SOCIEDADES                                                              1
FUNDAÇÃO PÚBLICA DE DIREITO PRIVADO ESTADUAL OU DO DISTRITO FEDERAL              1
Name: count, Length: 68, dtype: int64

In [22]:
df_atividades_economicas["porte_empresa"].value_counts()

porte_empresa
MICROEMPRESA - ME           825571
DEMAIS                      126369
EMPRESA DE PEQUENO PORTE     54749
Name: count, dtype: int64

In [19]:
df_atividades_economicas.query("cnpj == '51427102000552'")

,cnae_principal,descricao_cnae,cnae_secundarias,natureza_juridica,porte_empresa,area_utilizada,ind_simples,ind_mei,tipo_unidade,forma_atuacao,desc_logradouro,nome_logradouro,numero_imovel,complemento,nome_bairro,nome,nome_fantasia,cnpj,data_inicio_atividade,nome_regional,geometria,urlfile,ind_possui_alvara
index,,,,,,,,,,,,,,,,,,,,,,,
51981,6619304.0,CAIXAS ELETRONICOS,nan,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,2.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,PROFESSOR ESTEVAO PINTO,830,nan,SERRA,TECNOLOGIA BANCARIA S.A,nan,51427102000552,18/05/2001,CENTRO-SUL,POINT (612812.8219499 7794497.91036454),20220601_atividade_economica.csv,nan
51982,6619304.0,CAIXAS ELETRONICOS,nan,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,2.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,DO CONTORNO,6619,nan,SANTO ANTONIO,TECNOLOGIA BANCARIA S.A,nan,51427102000552,04/01/2001,CENTRO-SUL,POINT (610990.39807364 7794799.17092164),20220601_atividade_economica.csv,nan
51983,6619304.0,CAIXAS ELETRONICOS,nan,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,MARIA AMELIA MAIA,811,nan,SAO BERNARDO,TECNOLOGIA BANCARIA S.A,nan,51427102000552,02/02/2000,NORTE,POINT (610697.884926454 7805264.82673433),20220601_atividade_economica.csv,nan
51984,6619304.0,CAIXAS ELETRONICOS,nan,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,RUA,ERICO VERISSIMO,1685,nan,SANTA MONICA,TECNOLOGIA BANCARIA S.A,nan,51427102000552,04/01/2001,VENDA NOVA,POINT (607169.073629446 7808424.30107708),20220601_atividade_economica.csv,nan
51985,6619304.0,CAIXAS ELETRONICOS,nan,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,2.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,CRISTIANO MACHADO,2250,nan,CIDADE NOVA,TECNOLOGIA BANCARIA S.A,nan,51427102000552,03/11/2000,NORDESTE,POINT (612125.272379601 7800604.93007157),20220601_atividade_economica.csv,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987623,6311900.0,"TRATAMENTO DE DADOS, PROVEDORES DE SERVIÇOS DE...",6311900,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,BEC,RAUL SOARES,70,nan,VILA ANTENA,TECNOLOGIA BANCARIA S.A.,nan,51427102000552,07-08-2025,nan,POINT (608515.72 7793925.83),20251001_atividade_economica.csv,NÃO
987624,6311900.0,"TRATAMENTO DE DADOS, PROVEDORES DE SERVIÇOS DE...",6311900,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,PCA,RUI BARBOSA,50,"NÃ?MERO:0,ANEXO:PC 56532",CENTRO,TECNOLOGIA BANCARIA S.A.,nan,51427102000552,07-08-2025,nan,POINT (611594.68 7797470.97),20251001_atividade_economica.csv,NÃO
987625,6311900.0,"TRATAMENTO DE DADOS, PROVEDORES DE SERVIÇOS DE...",6311900,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,PCA,RUI BARBOSA,50,"NÃ?MERO:0,ANEXO:PC 56556",CENTRO,TECNOLOGIA BANCARIA S.A.,nan,51427102000552,07-08-2025,nan,POINT (611594.68 7797470.97),20251001_atividade_economica.csv,NÃO
987627,6311900.0,"TRATAMENTO DE DADOS, PROVEDORES DE SERVIÇOS DE...",6311900,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,NOSSA SENHORA DE FATIMA,1518,"NÃ?MERO:1295,ANEXO:PC 56011",CARLOS PRATES,TECNOLOGIA BANCARIA S.A.,nan,51427102000552,07-08-2025,nan,POINT (610437.08 7797738.12),20251001_atividade_economica.csv,NÃO
987628,6311900.0,"TRATAMENTO DE DADOS, PROVEDORES DE SERVIÇOS DE...",6311900,SOCIEDADE ANÔNIMA FECHADA,DEMAIS,1.0,N,N,UNIDADE PRODUTIVA,ESTABELECIMENTO FIXO,AVE,NOSSA SENHORA DE FATIMA,1518,"NÃ?MERO:1295,ANEXO:PC 56288",CARLOS PRATES,TECNOLOGIA BANCARIA S.A.,nan,51427102000552,07-08-2025,nan,POINT (610437.08 7797738.12),20251001_atividade_economica.csv,NÃO